{
  "hash": "496f9e1c622d9e992b1bf36a19a08583",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Oscar Luo\"\ndate: \"Sept. 4th, 2026\"\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n\n**In this analysis, I look at the number with a bachelor's degree across counties in New York State, and ask which communities we measure most and least reliably.**\n\n---\n\n## Choosing what to measure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"NY\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B15003_022\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                         variable   estimate   moe\n  <chr> <chr>                        <chr>         <dbl> <dbl>\n1 36001 Albany County, New York      B15003_022    49653  1534\n2 36003 Allegany County, New York    B15003_022     3787   306\n3 36005 Bronx County, New York       B15003_022   130281  3296\n4 36007 Broome County, New York      B15003_022    21526  1008\n5 36009 Cattaraugus County, New York B15003_022     6055   387\n6 36011 Cayuga County, New York      B15003_022     7436   457\n```\n\n\n:::\n:::\n\nThe dataset contains 62 rows, one for each county in New York State, which matches the state’s 62 counties.\n\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                        estimate   moe moe_pct\n   <chr>                          <dbl> <dbl>   <dbl>\n 1 Hamilton County, New York        586    99   16.9 \n 2 Schuyler County, New York       1570   206   13.1 \n 3 Yates County, New York          2427   269   11.1 \n 4 Essex County, New York          4885   541   11.1 \n 5 Fulton County, New York         5111   541   10.6 \n 6 Sullivan County, New York       9476   986   10.4 \n 7 Montgomery County, New York     3888   400   10.3 \n 8 Washington County, New York     5649   573   10.1 \n 9 Chenango County, New York       3554   353    9.93\n10 Lewis County, New York          2060   203    9.85\n```\n\n\n:::\n:::\n\nHamilton County has the largest margin of error relative to its estimate. Its margin of error is approximately 16.9% of the estimated number of residents whose highest educational attainment is a bachelor’s degree, making it the least reliably measured county for this variable.\n\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    24\n2 Low confidence      8\n3 Moderate           30\n```\n\n\n:::\n:::\n\nOf New York State’s 62 counties, 24 fall into the high-confidence category, 30 are classified as moderate, and 8 fall into the low-confidence category.\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                         myvarE myvarM    popE  popM\n  <chr> <chr>                         <dbl>  <dbl>   <dbl> <dbl>\n1 36001 Albany County, New York       49653   1534  315374    NA\n2 36003 Allegany County, New York      3787    306   47027    NA\n3 36005 Bronx County, New York       130281   3296 1419250    NA\n4 36007 Broome County, New York       21526   1008  197738    NA\n5 36009 Cattaraugus County, New York   6055    387   76479    NA\n6 36011 Cayuga County, New York        7436    457   75464    NA\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         24        730694.\n2 Low confidence           8         40855.\n3 Moderate                30         66961.\n```\n\n\n:::\n:::\n\nThe 24 high-confidence counties have an average population of approximately 730,694, compared with 66,961 for the 30 moderate-confidence counties and 40,855 for the 8 low-confidence counties. This pattern suggests that more populous counties tend to have more reliable ACS estimates, while smaller counties tend to have larger margins of error relative to their estimates.\n\n---\n\n## What this means for policy\n\nAmong all the counties in New York State, Hamilton County has the least reliable estimate: 586 residents aged 25 or older were estimated to have a bachelor’s degree as their highest level of education, with a margin of error of 99, or 16.9% of the estimate. Schuyler County follows with a relative margin of error of 13.1%, while Yates and Essex Counties are both about 11.1%. Overall, eight counties fall into the low-confidence category.\n\nThis reflects how the American Community Survey (ACS) works. The ACS estimates population characteristics from a sample rather than counting every resident. Smaller counties contribute fewer sampled households and residents, so each response carries more weight and the estimates have greater uncertainty. In this analysis, low-confidence counties have an average population of 40,855, compared with 730,694 in high-confidence counties.\n\nIgnoring this margin of error might lead to unfair policy decisions. If a state agency directed workforce-development funding toward counties with fewer bachelor’s degree holders, it might treat every county estimate as equally precise. If a small county’s bachelor’s degree count were overestimated, it could appear better educated and receive less support than it needs as the result. Rural counties such as Hamilton, Schuyler, and Yates are especially vulnerable because their limited sample sizes make their estimates less stable. Agencies should  consider margins of error and avoid making funding decisions based on small differences alone.\n\n---\n\n## Optional challenges - For those craving more\n\n**Challenge 4: To examine how geographic scale affects uncertainty, I repeated the analysis for census tracts within Onondaga County, New York, which includes the city of Syracuse.**\n\n::: {.cell}\n\n```{.r .cell-code}\ntract_data <- get_acs(\n  geography = \"tract\",\n  variables = my_variable,\n  state = my_state,\n  county = \"Onondaga\",\n  year = 2023,\n  survey = \"acs5\"\n)\n\ndim(tract_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 142   5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(tract_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID       NAME                                       variable estimate   moe\n  <chr>       <chr>                                      <chr>       <dbl> <dbl>\n1 36067000100 Census Tract 1; Onondaga County; New York  B15003_…      383   137\n2 36067000200 Census Tract 2; Onondaga County; New York  B15003_…      213   118\n3 36067000300 Census Tract 3; Onondaga County; New York  B15003_…      177    64\n4 36067000400 Census Tract 4; Onondaga County; New York  B15003_…      500   182\n5 36067000501 Census Tract 5.01; Onondaga County; New Y… B15003_…      268   148\n6 36067000600 Census Tract 6; Onondaga County; New York  B15003_…      214   128\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntract_data <- tract_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n\ntract_data %>%\n  summarize(\n    n_tracts = n(),\n    median_moe_pct = median(moe_pct),\n    mean_moe_pct = mean(moe_pct),\n    min_moe_pct = min(moe_pct),\n    max_moe_pct = max(moe_pct)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  n_tracts median_moe_pct mean_moe_pct min_moe_pct max_moe_pct\n     <int>          <dbl>        <dbl>       <dbl>       <dbl>\n1      142           32.1         37.3        14.3        103.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  filter(NAME == \"Onondaga County, New York\") %>%\n  select(NAME, estimate, moe, moe_pct)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  NAME                      estimate   moe moe_pct\n  <chr>                        <dbl> <dbl>   <dbl>\n1 Onondaga County, New York    68569  2067    3.01\n```\n\n\n:::\n:::\n\nAt the county level, Onondaga County has an estimated 68,569 residents aged 25 or older whose highest educational attainment is a bachelor’s degree, with a relative margin of error of approximately 3.0%. Across its 142 census tracts, however, the median relative margin of error is 32.1% and the mean is 37.3%, with values ranging from 14.3% to 103.1%. This comparison shows that ACS estimates become much less precise at smaller geographic scales because each tract is represented by a smaller sample.\n\n---\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}